spring:
  application:
    name: user-service

  datasource:
    url: jdbc:mysql://localhost:3306/springBoot
    username: alex
    password: 1234

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

  threads:
    virtual:
      enabled: true


server:
  port: 8090
  servlet:
    context-path: /
  error:
    include-stacktrace: ON_PARAM
  tomcat:
    threads:
      max: 20


