spring:
  application:
    name: anime-service

  threads:
    virtual:
      enabled: true


server:
  port: 8090
  servlet:
    context-path: /
  error:
    include-stacktrace: ON_PARAM
  tomcat:
    threads:
      max: 20


database:
  url: ${DB_URL:localhost}:${DB_PORT:3306}
  username: ${LOCAL_USERNAME:alex}
  password: ${LOCAL_PASSWORD:12345}